spring:
  application:
    name: nginx-tests

nginx:
  work-dir: ${WORK_DIR:/home/papa/IdeaProjects/grant-access-nginx/nginx}
  port-prefix: ${PORT_PREFIX:13}
  default-http-port: ${DEFAULT_HTTP_PORT:13081}
  host: ${HOST:localhost}

